# Generated by Django 2.0.4 on 2018-04-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0002_auto_20180422_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=140)),
                ('county_id', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CountyPop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.County')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=140)),
                ('indicator_id', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=140)),
                ('state_id', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='StatePop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.Indicator')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.State')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='statepop',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.Year'),
        ),
        migrations.AddField(
            model_name='countypop',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.Indicator'),
        ),
        migrations.AddField(
            model_name='countypop',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.Year'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.State'),
        ),
    ]
