# Generated by Django 2.0.4 on 2018-04-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0004_auto_20180423_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statepop',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
