# Generated by Django 2.0.4 on 2018-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0006_auto_20180423_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='geometry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='geometry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
