# Generated by Django 2.0.4 on 2018-04-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0007_auto_20180424_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_short_name',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
