# Generated by Django 2.0.4 on 2018-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0008_state_state_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countypop',
            name='population',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='statepop',
            name='population',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
