# Generated by Django 2.0.4 on 2018-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_scraping', '0008_state_state_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('chart_type', models.CharField(choices=[('BAR', 'Bar Chart'), ('GEO', 'Geo Chart'), ('LINE', 'Line Chart')], default='GEO', max_length=32)),
                ('indicator', models.ManyToManyField(to='data_scraping.Indicator')),
            ],
        ),
    ]
