# Generated by Django 2.0.4 on 2018-04-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
