# Generated by Django 2.0.4 on 2018-04-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_visual', '0002_visual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
