# Generated by Django 2.0.4 on 2018-04-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_visual', '0004_auto_20180427_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='short_title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
