# Generated by Django 2.0.4 on 2018-04-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_visual', '0005_visual_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visual',
            name='chart_type',
            field=models.CharField(choices=[('PNG', 'Picture'), ('BAR', 'Bar Chart'), ('GEO', 'Geo Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart')], default='GEO', max_length=32),
        ),
    ]
